name: cinetime
description: CinéTime
version: 2.2.5+54

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Framework Tools
  rxdart: ^0.27.2

  # Data management
  shared_preferences: ^2.0.8

  # Widgets / UI
  flash: ^2.0.3
  flutter_spinkit: ^5.1.0
  shimmer: ^2.0.0
  fading_edge_scrollview: ^2.0.1
  photo_view: ^0.13.0
  video_player: ^2.2.5
  chewie: ^1.2.2

  # Web
  http: ^0.13.4
  connectivity_plus: ^2.0.2
  flutter_cache_manager: ^3.1.2
  cached_network_image: ^3.1.0
  amplitude_flutter: ^3.5.0

  # Device
  device_info_plus: ^3.1.0
  sentry_flutter: ^6.0.1
  url_launcher: ^6.0.12
  share_plus: ^3.0.4
  geolocator: 7.6.2  # Next version needs compileSdkVersion = 31
  add_2_calendar: ^2.1.2

  # Internationalization
  intl: ^0.17.0
  timeago: ^3.1.0

  # The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: CineTimeIcons
      fonts:
        - asset: assets/CineTimeIcons.ttf
