name: cinetime
description: CinéTime
version: 2.13.1+84

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Framework Tools
  value_stream_flutter: ^1.0.0
  collection: ^1.19.1

  # Data management
  shared_preferences: ^2.5.3

  # Widgets / UI
  flash: ^3.1.1
  font_awesome_flutter: ^10.9.1
  flutter_spinkit: ^5.2.2
  shimmer: ^3.0.0
  linked_scroll_controller: ^0.2.0
  fading_edge_scrollview: ^4.1.1
  photo_view: ^0.15.0
  chewie: ^1.12.1

  # Web
  http: ^1.5.0
  connectivity_plus: ^6.1.5
  flutter_cache_manager: ^3.4.1
  cached_network_image: ^3.4.1
  amplitude_flutter: ^4.3.7

  # Device
  device_info_plus: ^11.5.0
  in_app_update: ^4.2.3
  sentry_flutter: ^9.6.0
  url_launcher: ^6.3.2
  share_plus: ^11.1.0
  geolocator: ^14.0.2
  add_2_calendar: ^3.0.1

  # Internationalization
  intl: ^0.20.2
  timeago: ^3.7.1
  diacritic: ^0.1.6

dev_dependencies:
  flutter_lints: ^6.0.0

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
