name: cinetime
description: CinéTime
version: 2.10.0+80

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Framework Tools
  value_stream: ^0.2.0
  collection: 1.18.0  # Next update requires higher Flutter version

  # Data management
  shared_preferences: ^2.3.2

  # Widgets / UI
  flash: ^3.1.1
  flutter_spinkit: ^5.2.1
  shimmer: ^3.0.0
  fading_edge_scrollview: ^4.1.1
  photo_view: ^0.15.0
  chewie: ^1.8.5

  # Web
  http: ^1.2.2
  connectivity_plus: ^6.1.0
  flutter_cache_manager: 3.3.1    # Next version requires rxdart > 0.26.0
  cached_network_image: 3.3.1     # Next version requires higher flutter_cache_manager version
  amplitude_flutter: ^3.16.4

  # Device
  device_info_plus: ^11.1.0
  in_app_update: ^4.2.3
  sentry_flutter: 8.3.0
  url_launcher: ^6.3.1
  share_plus: ^10.1.1
  geolocator: ^13.0.1
  add_2_calendar: ^3.0.1

  # Internationalization
  intl: ^0.19.0
  timeago: ^3.7.0
  diacritic: ^0.1.6

dev_dependencies:
  flutter_lints: ^4.0.0

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: CineTimeIcons
      fonts:
        - asset: assets/CineTimeIcons.ttf
