name: cinetime
description: CinéTime
version: 2.13.0+83

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Framework Tools
  value_stream: ^0.2.0
  collection: ^1.19.1

  # Data management
  shared_preferences: ^2.5.3

  # Widgets / UI
  flash: ^3.1.1
  font_awesome_flutter: ^10.8.0
  flutter_spinkit: ^5.2.1
  shimmer: ^3.0.0
  linked_scroll_controller: ^0.2.0
  fading_edge_scrollview: ^4.1.1
  photo_view: ^0.15.0
  chewie: ^1.11.3

  # Web
  http: ^1.3.0
  connectivity_plus: ^6.1.4
  flutter_cache_manager: ^3.4.1
  cached_network_image: ^3.4.1
  amplitude_flutter: ^4.3.1

  # Device
  device_info_plus: ^11.4.0
  in_app_update: ^4.2.3
  sentry_flutter: ^8.14.2
  url_launcher: ^6.3.1
  share_plus: ^10.1.4
  geolocator: ^13.0.4
  add_2_calendar: ^3.0.1

  # Internationalization
  intl: ^0.19.0
  timeago: ^3.7.0
  diacritic: ^0.1.6

dev_dependencies:
  flutter_lints: ^4.0.0

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
