name: cinetime
description: CinéTime
version: 2.0.0+40

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Framework Tools
  rxdart: ^0.27.1
  provider: ^5.0.0

  # Data management
  shared_preferences: ^2.0.6
  json_annotation: ^3.1.1

  # Widgets / UI
  flash: ^1.3.1
  font_awesome_flutter: ^8.10.0
  flutter_spinkit: ^4.1.2+1
  scaling_header: ^1.1.1
  marquee_widget: ^0.8.0
  shimmer: ^1.1.2
  flutter_layout_grid: ^0.10.2
  fading_edge_scrollview: ^1.1.4
  flutter_easyrefresh: ^2.1.6
  flutter_xlider: ^3.4.0
  smooth_star_rating: ^1.1.1
  video_player: ^2.1.4
  chewie: ^1.2.0

  # Web
  http: ^0.13.3
  flutter_cache_manager: ^3.1.0
  cached_network_image: ^3.0.0
  crypto: ^3.0.1

  # Device
  url_launcher: ^6.0.4
  share_plus: ^2.1.2
  geolocator: ^7.0.3

  # Internationalization
  intl: ^0.16.1
  timeago: ^2.0.27

dev_dependencies:
  build_runner: ^1.10.6
  json_serializable: ^3.5.0

  # The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages