name: cinetime
description: CinéTime
version: 2.8.0+70

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Framework Tools
  rxdart: 0.26.0  # Stuck on this version for now : https://github.com/ReactiveX/rxdart/issues/603

  # Data management
  shared_preferences: ^2.2.0

  # Widgets / UI
  flash: ^3.0.5+1
  flutter_spinkit: ^5.2.0
  shimmer: ^3.0.0
  fading_edge_scrollview: ^3.0.0
  photo_view: ^0.14.0
  chewie: ^1.5.0

  # Web
  http: ^0.13.6  # Next version requires flutter_cache_manager > 3.3.0
  connectivity_plus: ^3.0.6  # Next version requires minSdkVersion >= 19
  flutter_cache_manager: ^3.3.1
  cached_network_image: ^3.2.3
  amplitude_flutter: ^3.16.0

  # Device
  device_info_plus: ^8.2.2  # Next version requires minSdkVersion >= 19
  sentry_flutter: 7.5.2    # Next version requires minSdkVersion >= 19
  url_launcher: ^6.1.11
  share_plus: ^6.3.4  # Next version requires minSdkVersion >= 19
  geolocator: ^9.0.2
  add_2_calendar: ^2.2.4

  # Internationalization
  intl: ^0.18.1
  timeago: ^3.5.0
  diacritic: ^0.1.4

  # Other
  file: ^6.1.4  # TEMP Not used directly, but needed to force dependencies to use updated version

dev_dependencies:
  flutter_lints: ^2.0.2

dependency_overrides:
  # TEMP fix
  # See https://github.com/creativecreatorormaybenot/wakelock/issues/202#issuecomment-1545880072
  wakelock:
    git:
      url: https://github.com/miguelmato/wakelock
      ref: main
      path: wakelock

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: CineTimeIcons
      fonts:
        - asset: assets/CineTimeIcons.ttf
