name: cinetime
description: CinéTime
version: 2.4.0+58

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Framework Tools
  rxdart: 0.26.0  # Stuck on this version for now : https://github.com/ReactiveX/rxdart/issues/603

  # Data management
  shared_preferences: ^2.0.15

  # Widgets / UI
  flash: ^2.0.3+2
  flutter_spinkit: ^5.1.0
  shimmer: ^2.0.0
  fading_edge_scrollview: ^3.0.0
  photo_view: ^0.14.0
  chewie: ^1.3.3

  # Web
  http: ^0.13.4
  connectivity_plus: ^2.3.4
  flutter_cache_manager: ^3.3.0
  cached_network_image: ^3.2.1
  amplitude_flutter: ^3.10.0

  # Device
  device_info_plus: ^3.2.4
  sentry_flutter: ^6.5.1
  url_launcher: 6.0.20  # Next version has breaking changes
  share_plus: ^4.0.8
  geolocator: ^8.2.1
  add_2_calendar: ^2.1.3

  # Internationalization
  intl: ^0.17.0
  timeago: ^3.2.2
  diacritic: ^0.1.3

dev_dependencies:
  flutter_lints: ^2.0.1

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: CineTimeIcons
      fonts:
        - asset: assets/CineTimeIcons.ttf
