name: cinetime
description: CinéTime
version: 2.0.0+40

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Framework Tools
  rxdart: ^0.24.1
  provider: ^4.3.2+2

  # Data management
  shared_preferences: ^0.5.12
  json_annotation: ^3.1.0

  # Widgets / UI
  flash: ^1.3.1
  font_awesome_flutter: ^8.8.1
  flutter_spinkit: ^4.1.2+1
  scaling_header: ^1.1.1
  marquee_widget: ^0.8.0
  shimmer: ^1.1.1
  flutter_layout_grid: ^0.10.2
  fading_edge_scrollview: ^1.1.4
  flutter_easyrefresh: ^2.1.5
  flutter_xlider: ^3.4.0
  smooth_star_rating: ^1.1.1
  video_player: 0.10.12+5   # Can't update while chewie <= 0.9.10
  chewie: ^0.9.10

  # Web
  http: ^0.12.2
  connectivity: ^0.4.9+3
  flutter_cache_manager: ^1.4.2
  cached_network_image: ^2.3.2+1
  crypto: ^2.1.5

  # Device
  url_launcher: ^5.7.2
  share: ^0.6.5+2
  geolocator: ^6.0.0+4

  # Other
  intl: ^0.16.1
  timeago: ^2.0.27

dev_dependencies:
  build_runner: 1.10.1   # Higher versions needs higher Flutter version (>1.20.2) (SDK version >=2.10.0)
  json_serializable: ^3.5.0

  # The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages